export const ADD_LIKE = 'ADD_LIKE';
export const REMOVE_LIKE = 'REMOVE_LIKE';
export const REQUEST_GIF = 'REQUEST_GIF';
export const RECEIVE_GIF = 'RECEIVE_GIF';
export const UPDATE_WEIRDNESS_SCORE = 'UPDATE_WEIRDNESS_SCORE';
export const REMOVE_ALL_LIKES = 'REMOVE_ALL_LIKES';
export const INVALID_SEARCH = 'INVALID_SEARCH';
export const FETCH_GIF = 'FETCH_GIF';
